on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Confirm README.md is up to date.
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          working-dir: .
          fail-on-diff: true

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: terraform-module
